import { GoogleGenAI } from "@google/genai";
import { ViewGenerationResult } from '../../types/dungeon';

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY as string });

export const generateDungeonView = async (imageBase64: string): Promise<ViewGenerationResult> => {
  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image', // Fast, good for recurring game images
      contents: {
        parts: [
          {
            inlineData: {
              mimeType: 'image/png',
              data: imageBase64,
            },
          },
          {
            text: `
              Convert this 2D top-down mini-map into a photorealistic first-person perspective 3D view from eye level.

              Legend:
              - The yellow cone/triangle at the center is the player/camera, facing UP.
              - Dark blue/black blocks are stone walls.
              - Light gray blocks are the stone floor/path.
              - Red block is the Exit (a glowing magical portal).

              Instructions:
              - Render exactly what the player sees directly in front of them based on the map.
              - If there is a wall directly ahead, show a wall close up.
              - If there is a hallway, show the hallway extending.
              - If the red block is visible, show a glowing red portal.
              - Style: Dark, moody, medieval dungeon. Torchlight flickering.
              - Output ONLY the visual scene. Do not include the map overlay.
              - Perspective: Eye-level, 1st person.
            `
          }
        ]
      },
      config: {
        // Flash image model doesn't support system instructions or schema effectively in the same way,
        // so we rely on the prompt.
      }
    });

    let imageUrl = '';
    let narrative = '';

    if (response.candidates?.[0]?.content?.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
          imageUrl = `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
        } else if (part.text) {
          narrative = part.text;
        }
      }
    }

    // If no image returned (fallback if model refuses or just talks), return a placeholder or retry
    if (!imageUrl) {
        console.warn("No image generated by Gemini, using placeholder text.");
        return { imageUrl: '', narrative: "The darkness is too thick to see... (API did not return image)" };
    }

    return { imageUrl, narrative };

  } catch (error) {
    console.error("Gemini API Error:", error);
    throw error;
  }
};