import React, { useState } from 'react';
import { ArrowLeft, Lightbulb, BookOpen, Target, Layers, Book, Download } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { YouTubeAnalysisResult, YouTubeStatus } from '../types/youtube';
import { YouTubeInput } from './youtube/YouTubeInput';
import { YouTubeQuiz } from './youtube/YouTubeQuiz';

interface YouTubeLearningProps {
  onBack: () => void;
}

export const YouTubeLearning: React.FC<YouTubeLearningProps> = ({ onBack }) => {
  const { t } = useTranslation(['common', 'youtube']);
  const [status, setStatus] = useState<YouTubeStatus>(YouTubeStatus.IDLE);
  const [result, setResult] = useState<YouTubeAnalysisResult | null>(null);
  const [error, setError] = useState<string | null>(null);

  const handleAnalyze = async (text: string) => {
    setStatus(YouTubeStatus.PROCESSING);
    setError(null);
    try {
      // Call backend API endpoint instead of analyzing directly
      const response = await fetch('/api/analyze-youtube', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ transcript: text }),
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.details || errorData.error || 'Failed to analyze content');
      }

      const data = await response.json();
      setResult(data);
      setStatus(YouTubeStatus.COMPLETED);
    } catch (err: any) {
      console.error(err);
      setError(err.message || "Something went wrong. Please check your API key and try again.");
      setStatus(YouTubeStatus.ERROR);
    }
  };

  const handleReset = () => {
    setStatus(YouTubeStatus.IDLE);
    setResult(null);
    setError(null);
  };

  const handleDownloadReport = () => {
    if (!result) return;

    // Generate formatted report
    let report = `# ${result.title}\n\n`;
    report += `## ${t('youtube:analysisReport', 'Analysis Report')}\n\n`;

    // Main Focus
    report += `### ${t('youtube:mainFocus', 'Main Focus')}\n`;
    report += `${result.mainFocus}\n\n`;

    // Key Teachings
    report += `### ${t('youtube:keyTeachings', 'Key Teachings')}\n`;
    result.keyTeachings.forEach((teaching, idx) => {
      report += `${idx + 1}. ${teaching}\n`;
    });
    report += '\n';

    // Theological Insights
    report += `### ${t('youtube:theologicalInsights', 'Theological Insights')}\n`;
    result.theologicalInsights.forEach((insight, idx) => {
      report += `${idx + 1}. ${insight}\n`;
    });
    report += '\n';

    // Biblical References
    report += `### ${t('youtube:biblicalReferences', 'Biblical References')}\n`;
    result.biblicalReferences.forEach((ref) => {
      report += `- ${ref}\n`;
    });
    report += '\n';

    // Practical Applications
    report += `### ${t('youtube:practicalApplications', 'Practical Applications')}\n`;
    report += `${result.practicalApplications}\n\n`;

    // Quiz
    report += `### ${t('youtube:quiz', 'Quiz')}\n\n`;
    result.quiz.forEach((q, idx) => {
      report += `**Question ${idx + 1}:** ${q.question}\n`;
      report += `Type: ${q.type}\n`;
      report += `Options:\n`;
      q.options.forEach((opt, optIdx) => {
        const isCorrect = optIdx === q.correctAnswerIndex;
        report += `  ${String.fromCharCode(65 + optIdx)}. ${opt}${isCorrect ? ' ✓' : ''}\n`;
      });
      report += '\n';
    });

    report += `\n---\n`;
    report += `Generated by AI Sunday School - YouTube Learning\n`;
    report += `${new Date().toLocaleString()}\n`;

    // Create and download file
    const blob = new Blob([report], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `youtube-analysis-${new Date().toISOString().split('T')[0]}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen bg-slate-50 py-12 px-4 sm:px-6 lg:px-8 font-sans text-slate-900">
      {/* Header with Back Button */}
      {status === YouTubeStatus.IDLE && (
        <div className="max-w-7xl mx-auto mb-8">
          <button
            onClick={onBack}
            className="flex items-center gap-2 text-slate-600 hover:text-red-600 transition-colors font-medium"
          >
            <ArrowLeft className="w-5 h-5" />
            <span>{t('common:buttons.backToHome', 'Back to Home')}</span>
          </button>
        </div>
      )}

      {status === YouTubeStatus.IDLE || status === YouTubeStatus.PROCESSING || status === YouTubeStatus.ERROR ? (
        <div className="flex flex-col items-center">
          <YouTubeInput onAnalyze={handleAnalyze} isLoading={status === YouTubeStatus.PROCESSING} />

          {status === YouTubeStatus.ERROR && (
            <div className="mt-6 p-4 bg-red-50 border border-red-200 text-red-700 rounded-lg max-w-xl text-center animate-pulse">
              {error}
            </div>
          )}
        </div>
      ) : (
        <div className="max-w-5xl mx-auto animate-slideUp pb-20">
           {result && (
             <div className="space-y-8">
                {/* Navigation / Back and Download */}
                <div className="flex items-center justify-between">
                  <button
                    onClick={handleReset}
                    className="text-slate-500 hover:text-red-600 font-medium flex items-center gap-1 transition-colors"
                  >
                    ← {t('youtube:backToAnalyzer', 'Back to Analyzer')}
                  </button>

                  <button
                    onClick={handleDownloadReport}
                    className="flex items-center gap-2 px-4 py-2 bg-red-600 hover:bg-red-700 text-white rounded-lg transition-colors shadow-sm"
                  >
                    <Download className="w-4 h-4" />
                    {t('youtube:downloadReport', 'Download Report')}
                  </button>
                </div>

                {/* Header Section */}
                <header className="bg-white p-8 rounded-2xl shadow-sm border border-slate-200">
                  <div className="uppercase tracking-wide text-red-600 font-bold text-sm mb-2">
                    {t('youtube:analysisReport', 'Analysis Report')}
                  </div>
                  <h1 className="text-3xl sm:text-4xl font-extrabold text-slate-900 leading-tight">
                    {result.title}
                  </h1>
                </header>

                {/* Main Focus Section */}
                <section className="bg-white p-8 rounded-2xl shadow-sm border border-slate-200 relative overflow-hidden">
                  <div className="absolute top-0 left-0 w-2 h-full bg-blue-500" />
                  <h2 className="text-xl font-bold text-slate-800 mb-4 flex items-center gap-2">
                    <Target className="w-6 h-6 text-blue-500" />
                    {t('youtube:mainFocus', 'Main Focus')}
                  </h2>
                  <div className="prose prose-slate max-w-none text-slate-600 leading-relaxed text-lg">
                    {result.mainFocus}
                  </div>
                </section>

                {/* Grid for Key Teachings & Theological Insights */}
                <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                  <section className="bg-white p-8 rounded-2xl shadow-sm border border-slate-200 h-full">
                    <h2 className="text-xl font-bold text-slate-800 mb-4 flex items-center gap-2">
                      <Lightbulb className="w-6 h-6 text-amber-500" />
                      {t('youtube:keyTeachings', 'Key Teachings')}
                    </h2>
                    <ul className="space-y-3">
                      {result.keyTeachings.map((teaching, idx) => (
                        <li key={idx} className="flex gap-3 text-slate-600">
                          <span className="text-amber-500 font-bold">•</span>
                          {teaching}
                        </li>
                      ))}
                    </ul>
                  </section>

                  <section className="bg-white p-8 rounded-2xl shadow-sm border border-slate-200 h-full">
                    <h2 className="text-xl font-bold text-slate-800 mb-4 flex items-center gap-2">
                      <Layers className="w-6 h-6 text-purple-500" />
                      {t('youtube:theologicalInsights', 'Theological Insights')}
                    </h2>
                     <ul className="space-y-3">
                      {result.theologicalInsights.map((insight, idx) => (
                        <li key={idx} className="flex gap-3 text-slate-600">
                          <span className="text-purple-500 font-bold">→</span>
                          {insight}
                        </li>
                      ))}
                    </ul>
                  </section>
                </div>

                {/* Biblical References & Practical Applications Grid */}
                 <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                  <section className="bg-white p-8 rounded-2xl shadow-sm border border-slate-200 h-full relative overflow-hidden">
                     <div className="absolute top-0 left-0 w-1 h-full bg-emerald-400" />
                    <h2 className="text-xl font-bold text-slate-800 mb-4 flex items-center gap-2">
                      <Book className="w-6 h-6 text-emerald-500" />
                      {t('youtube:biblicalReferences', 'Biblical References')}
                    </h2>
                     <ul className="space-y-3">
                      {result.biblicalReferences.map((ref, idx) => (
                        <li key={idx} className="bg-emerald-50 text-emerald-900 p-3 rounded-lg text-sm border border-emerald-100">
                          {ref}
                        </li>
                      ))}
                    </ul>
                  </section>

                  <section className="bg-white p-8 rounded-2xl shadow-sm border border-slate-200 h-full relative overflow-hidden">
                    <div className="absolute top-0 left-0 w-1 h-full bg-indigo-400" />
                    <h2 className="text-xl font-bold text-slate-800 mb-4 flex items-center gap-2">
                      <BookOpen className="w-6 h-6 text-indigo-500" />
                      {t('youtube:practicalApplications', 'Practical Applications')}
                    </h2>
                    <p className="text-slate-600 leading-relaxed">
                      {result.practicalApplications}
                    </p>
                  </section>
                </div>

                {/* Quiz Section */}
                <section className="bg-white p-8 rounded-2xl shadow-sm border border-slate-200 relative overflow-hidden">
                  <div className="absolute top-0 left-0 w-2 h-full bg-red-500" />
                  <YouTubeQuiz questions={result.quiz} onReset={handleReset} />
                </section>
             </div>
           )}
        </div>
      )}

      {/* Footer */}
      <footer className="mt-20 text-center text-slate-400 text-sm pb-8">
        <p>Powered by Google Gemini 2.5 Flash</p>
      </footer>
    </div>
  );
};
